<?php

declare(strict_types=1);

namespace Asannou\DohMasq;

class DomainListGenerator
{
    private array $sourceUrls;
    private string $outputFile;

    public function __construct(array $sourceUrls, string $outputFile)
    {
        $this->sourceUrls = $sourceUrls;
        $this->outputFile = $outputFile;
    }

    public function generate(bool $verbose = true): bool
    {
        if ($verbose) {
            echo "Domain list generator started...\n";
        }

        $final_domain_map = [];
        $totalBytes = 0;

        foreach ($this->sourceUrls as $url) {
            if ($verbose) {
                echo "Fetching from $url...\n";
            }
            $hostsContent = $this->fetchSourceContent($url);
            if ($hostsContent === null) {
                if ($verbose) {
                    echo "Warning: Failed to download hosts file from $url. Skipping.\n";
                }
                continue;
            }
            $bytes = strlen($hostsContent);
            $totalBytes += $bytes;
            if ($verbose) {
                echo "Download complete (" . $bytes . " bytes).\n";
            }

            $domain_map = $this->parseHostsContent($hostsContent);
            $final_domain_map = array_merge($final_domain_map, $domain_map);
        }

        if (empty($final_domain_map)) {
            if ($verbose) {
                echo "Error: No domains were parsed from any source. Aborting.\n";
            }
            return false;
        }

        if ($verbose) {
            echo "Total downloaded: $totalBytes bytes.\n";
            echo "Found " . count($final_domain_map) . " unique domains across all sources.\n";
        }

        $fileContent = $this->generatePhpFileContent($final_domain_map);

        if ($verbose) {
            echo "Generating $this->outputFile ...\n";
        }

        if ($this->saveOutputFile($fileContent) === false) {
            if ($verbose) {
                echo "Error: Failed to write to $this->outputFile. Check permissions.\n";
            }
            return false;
        }

        if ($verbose) {
            echo "Successfully created $this->outputFile.\n";
        }
        return true;
    }

    public function fetchSourceContent(string $url): ?string
    {
        $content = @file_get_contents($url);
        return $content === false ? null : $content;
    }

    public function parseHostsContent(string $hostsContent): array
    {
        $domain_map = [];
        $lines = explode("\n", $hostsContent);

        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line) || $line[0] === '#') {
                continue;
            }

            $commentPos = strpos($line, '#');
            if ($commentPos !== false) {
                $line = trim(substr($line, 0, $commentPos));
            }

            $parts = preg_split('/\s+/', $line);
            if (count($parts) < 2) {
                continue;
            }

            $ip = $parts[0];
            if (!filter_var($ip, FILTER_VALIDATE_IP)) {
                continue;
            }

            for ($i = 1; $i < count($parts); $i++) {
                $domain = strtolower(trim($parts[$i]));
                if ($domain === 'localhost') {
                    continue;
                }

                if ($ip === '0.0.0.0') {
                    $domain_map[$domain] = false; // Blocked
                } else {
                    $domain_map[$domain] = $ip; // Resolved to IP
                }
            }
        }
        return $domain_map;
    }

    public function generatePhpFileContent(array $domain_map): string
    {
        $arrayString = var_export($domain_map, true);

        $sourceUrlsString = implode("\n// - ", $this->sourceUrls);

        $fileContent = "<?php\n\n";
        $fileContent .= "// This file was automatically generated by " . basename(__FILE__) . "\n";
        $fileContent .= "// Generated on: " . date('Y-m-d H:i:s') . "\n";
        $fileContent .= "// Sources:\n// - $sourceUrlsString\n\n";
        $fileContent .= "return $arrayString;\n";

        return $fileContent;
    }

    public function saveOutputFile(string $content): bool
    {
        return file_put_contents($this->outputFile, $content) !== false;
    }
}
